### ISSUE TITLE
The initial modal dialog is too large and doesn't scroll

### ISSUE THREAD

**Issue by larsrc-google** [OpenRoberta/robertalab#169] opened 2016-07-15 09:55 UTC
On a laptop screen, the checkbox to not show the initial dialog is inaccessible. Fix: add overflow:auto to the .modal style.

**Comment by bjost2s** [comment] 2016-09-27 20:34
can you please provide the browser and system. For me windows and linux, chrome and firefox and on android it works fine

**Comment by larsrc-google** [comment] 2016-09-28 07:11
This was with Chrome on a fairly recent 13" MacBook Air - can't say the exact versions as I have updated since then.

**Comment by bjost2s** [comment] 2016-10-09 00:32
due to be not reproducable, I close this. Please open again if error occurs.

**Closed by bjost2s** 2016-10-09 00:32 UTC
Labels: bug
