### ISSUE TITLE
mvn clean install on branch master exits with error

### ISSUE THREAD

**Issue by kwollw** [OpenRoberta/robertalab#774] opened 2018-02-26 11:27 UTC
mvn clean install on branch master exits with error (RobotArdu failed)
**Running de.fhg.iais.roberta.ast.action.MotionParamTest** 
(3 Errors)

**Comment by bjost2s** [comment] 2018-02-26 21:19
I cannot reproduce this error, please try
`mvn clean install -U`
If this is still not working, please clone the repo again and run 
`mvn clean install`

**Comment by VinArt** [comment] 2018-02-28 10:18
I just wonder.. Are you using AMD or Intel CPU?

**Comment by kwollw** [comment] 2018-02-28 15:30
Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz, 64 bit

**Comment by VinArt** [comment] 2018-02-28 15:33
It was off-topic. So maven executes tests non-deterministically and the order may vary from platform to platform. We have an issue of dependency between different tests that we are solving now. So I asked because I wonder what affects the order of execution.

**Comment by bjost2s** [comment] 2018-03-01 11:14
Please use `mvn clean install -DskipTests`  to build the project until we found a solution for this.

**Comment by rbudde** [comment] 2018-03-01 11:24
I can reproduce your problem.
As Artem already wrote, we have (unwanted) dependencies between tests (due to a static variable :-<). I'll scan the tests for this erroneous pattern + remove the occurences till Tuesday. Until this has been done, pls skip the tests as Beate proposed.

Thank you very much for your ticket!

**Comment by rbudde** [comment] 2018-03-01 12:54
I committed bf497ddf8f929d6cbb45e931192448639c52ed51 in branch develop. You'll get the changes if you pull develop. Can you check whether the error is gone? On my machine everything is fine now.

**Comment by kwollw** [comment] 2018-03-01 14:18
I confirm that mvn clean install on branch develop makes build successful on my machine too.

**Comment by rbudde** [comment] 2018-03-09 12:53
see #336 (the same bug)

**Comment by rbudde** [comment] 2018-03-12 12:34
Solved

**Closed** 2018-04-05 16:35 UTC
Labels: bug, resolved
