### ISSUE TITLE
Bug? Layout OR-Lab within chrome browser

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#907] opened 2018-06-05 06:26 UTC
Different layout representation chrome / firefox.
If I remember correctly, the OR-Lab looked uniform until the last release (like it is now only in Firefox)...

![image](https://user-images.githubusercontent.com/19221359/40958535-f1f1a990-6899-11e8-89c2-afb1909204a1.png)

![image](https://user-images.githubusercontent.com/19221359/40958555-037fc782-689a-11e8-8055-c5e1c62b1149.png)

**Comment by bjost2s** [comment] 2018-06-05 13:47
I only can reproduce this behaviour, if I click on ok in the footer. If this is not shown (because I have clicked before on ok and reloaded the page) I don't see this behaviour. Maybe the footer is changing something. Which version of firefox you use? and which system?

**Comment by Thorlogy** [comment] 2018-06-05 13:53
The firefox version (is the second screenshot) looks fine to me. It is the chrome version which looks buggy.

![image](https://user-images.githubusercontent.com/19221359/40980330-6954a59e-68d8-11e8-9f3a-ff96208c8954.png)
![image](https://user-images.githubusercontent.com/19221359/40980410-9be56a5c-68d8-11e8-9ff6-5a9e31a53022.png)

**Comment by bjost2s** [comment] 2018-06-06 18:53
could you please provide one or more full screenshots of the whole screen, that we can see at what stage this happens. Is it after the disclaimer was clicked (ok or x?) or is the start popup still visible?

I cannot reproduce this error, running chromium 66.0.3359.181

@all who can reproduce this issue?

**Comment by ensonic** [comment] 2018-06-06 20:57
I can repro it, screenshot with the respective element below. If I manually change with=1745px it looks good.

![screenshot from 2018-06-06 22-55-08](https://user-images.githubusercontent.com/1279486/41064733-bd462dd0-69dc-11e8-9a78-cf295a4081e7.png)

**Comment by bjost2s** [comment] 2018-06-07 12:23
could you please check this again on localhost and on test.open-roberta.org? I just want to make sure that it is not caused by the matamo snipplet. Because I cannot see it and I have blocked matamo

**Comment by ensonic** [comment] 2018-06-10 13:35
It is not happening on lab.open-roberta.org anymore and also test.open-roberta.org is good. I also tested the current git version and it looks good.

**Comment by bjost2s** [comment] 2018-06-17 13:42
There haven't been updates from our side in the last weeks, not on the lab.open-roberta.org for sure. Maybe an update from Chrome or Matamo?
@Thorlogy , can we close this, or do you still have this problem?

**Comment by Thorlogy** [comment] 2018-06-18 06:40
on my screen it is still existing:

![image](https://user-images.githubusercontent.com/19221359/41521605-137b9312-72d3-11e8-8bc5-ca3e77b5e09d.png)

**Comment by bjost2s** [comment] 2018-06-19 15:31
on lab.open-roberta.org and test.open-roberta.org the same?

**Comment by Thorlogy** [comment] 2018-06-22 07:00
The same
![image](https://user-images.githubusercontent.com/19221359/41762323-a5c628ac-75fa-11e8-87a0-969d881fdb8c.png)

**Comment by Thorlogy** [comment] 2018-06-25 05:51
@ensonic your right - since version 67.0.xxx the OR Lab  is displayed correctly again! Only the ORLab at the Test-Server is displayed like mentioned above.

**Comment by bjost2s** [comment] 2018-06-25 10:12
@Thorlogy, have you cleared the cache before accessing the testserver?

**Comment by Thorlogy** [comment] 2018-06-25 11:00
tried within the incognito mode and it looks like this:

![image](https://user-images.githubusercontent.com/19221359/41846683-c4046ec6-7877-11e8-85dd-cabd51575f4b.png)

**Comment by bjost2s** [comment] 2018-09-01 17:30
The reason for this strange behavior is probably the zoom factor. For 100% and 125% chrome returns an outer width including margin, but for 90% or 110% without. Other browser do it differently, but also have problems.
Fix is possible.

**Comment by rbudde** [comment] 2018-09-03 07:03
see my comment to #960 

"this seems to be another variant of the annoying problem with Chrome: if view is set to 110% e.g., the width information is delivered wrong by jquery (some other zoom level show the same behavior, others don't). This will hide tabs. If the window is resized (a bit), the tab re-appears.

This issue should be resolved!"

**Comment by rbudde** [comment] 2018-09-03 11:07
now fine

**Closed by rbudde** 2018-09-03 11:07 UTC
Labels: bug, resolved
